fix: 방 생성시 date를 시간순으로 저장
dnd-side-project/dnd-8th-5-backend pull request #61
Opened 2023-05-13 14:50 UTC by ssssujini99

closed #60 

## 어떤 기능을 개발했나요?
현재 상황 - 방 정보 조회 시 date가 무작위로 조회는데, 이를 정렬된 값을 반환하도록 하고자 합니다

## 어떻게 해결했나요?
방 생성시에 입력받은 date를 정렬을 먼저 시킨 후 저장하도록 하였습니다

## 어떤 부분에 집중하여 리뷰해야 할까요?

## (option) 이 부분은 주의해 주세요.

## (option) 참고자료

## (option) 결과

---

## RCA rule
- r: 꼭 반영해 주세요. 적극적으로 고려해 주세요.
- c: 웬만하면 반영해 주세요.
- a: 반영해도 좋고 안 해도 좋습니다. 사소한 의견입니다.
- 규칙
    - submit 할 코멘트들 중에서 1개라도 r이 포함되어 있다면 request change를 날린다.
    - r 이 하나도 없다면 approve를 한다.

2023-05-18 08:48 UTC, dongho108 requested changes
고생하셨습니다! 몇가지 리뷰 남겼으니 반영해주세요~

2023-05-18 08:48 UTC, dongho108 commented on src/test/java/com/dnd/modutime/core/room/domain/RoomTest.java
> +        Room room = getRoomByRoomDates(roomDates);
r: List.of말고 new ArrayList와 add로 초기화하는 방식을 바꾼 이유가 있을까요?

2023-05-18 08:48 UTC, dongho108 commented on src/main/java/com/dnd/modutime/core/room/domain/Room.java
> +        sortingByDate(roomDates);
date를 sort는 하는 메서드의 호출이 `validateRoomDates` 메서드 안에 있는게 맞을까요?
r: 생성자에서 검증을 다 끝낸후 할당 직전에 있으면 될 것 같아요!

2023-05-18 08:48 UTC, dongho108 commented on src/main/java/com/dnd/modutime/core/room/domain/Room.java
> +    private void sortingByDate(List<RoomDate> roomDates) {
r: 메서드 명은 동사로 시작한다는 코딩컨벤션을 지켜주세요!

참고 : https://naver.github.io/hackday-conventions-java/#method-verb-preposition | 2.10. 참고!

2023-05-18 08:55 UTC, ssssujini99 commented on src/main/java/com/dnd/modutime/core/room/domain/Room.java
> +        sortingByDate(roomDates);
아하 넵 같은 roomdate 내에서 검증해야한다고 생각했는데.
말씀 들어보니 검증 다 끝낸 후 할당 직전에 있으면 되는 부분인 것 같습니다
그거대로 메서드 위치만 바꿔놓겠습니다

2023-05-18 08:58 UTC, ssssujini99 commented on src/test/java/com/dnd/modutime/core/room/domain/RoomTest.java
> +        Room room = getRoomByRoomDates(roomDates);
roomdate를 정렬해야하는 부분에서 List.of( ) 로 생성하면 불변리스트라 에러가 발생해서
new ArrayList로 생성하고 add로 넣어주었습니다

2023-05-21 23:29 UTC, dongho108 requested changes
코드를 보니까 저장할때 정렬하는것보다 반환할때 하는게 더 좋을 것 같아요.

1. 반환할때 정렬하면 무조건 정렬 보장가능
2. 어차피 nlogn 이라 성능에 지장 없음
3. 불변 리스트 그대로 저장가능 (반환시 stream으로 dto 생성하면될듯)

지금은 저장할때 정렬하려고 하니 기존 테스트들도 다 수정해야하고, 프론트 요구사항 때문에 백엔드 도메인이 수정되는게 이상하긴 하네요..

2023-05-21 23:29 UTC, dongho108 commented on src/test/java/com/dnd/modutime/core/room/integration/RoomIntegrationTest.java
> +    void 방_생성시_date는_시간순으로_저장한다() {
r: 날짜순이라는 말이 더 정확할 것 같아요

2023-05-21 23:29 UTC, dongho108 commented on src/test/java/com/dnd/modutime/core/room/domain/RoomTest.java
> +        Room room = getRoomByRoomDates(roomDates);
생각해보니 방을 정렬해서 저장하더라도 반환할때 정렬된 날짜로 반환된다는 보장이 있을까요?
정렬로직은 해봤자 nlogn 일텐데 저장할땐 그대로 저장하고, 반환할때 정렬해서 반환하는게 더 나아보이긴 하네요. 수진님 생각은 어떠신가요?

c: 반환할때 정렬하면 불변리스트 그대로 사용할 수 있고, stream만 돌리고 DTO 만들어서 반환하면 돼서 더 편할 것 같아요.

2023-05-21 23:29 UTC, dongho108 commented on src/main/java/com/dnd/modutime/core/room/domain/Room.java
> +        sortByDate(roomDates);
할당 직전이 아니라 할당 직후에 있는 것 같아요.

2023-05-30 23:36 UTC, closed without merging