fix: 실시간 등록 현황 API에서 count 에러를 해결
dnd-side-project/dnd-8th-5-backend pull request #66
Opened 2023-05-14 19:23 UTC by ssssujini99

closed #62 

## 어떤 기능을 개발했나요?
정확히 말해서 참여자가 시간 교체시, TimeTable에 있는 participant에 참여자의 정보가 제대로 업데이트 되지 않아 실시간 등록 현황 API에서 count 값이 제대로 counting이 되지 않았습니다.
그래서 교체 시 TimeTable이 변경되는 부분에서 에러를 찾아 해결해, 실시간 등록 현황 조회 시 count 값이 제대로 반환하도록 하였습니다.

## 어떻게 해결했나요?
가장 문제가 되었던 부분은 다음과 같습니다.
```java
        for (Long timeInfoId : timeInfoIds) {
            timeInfoParticipantNameRepository.deleteByTimeInfoIdAndName(timeInfoId, event.getParticipantName());
        }
        timeTable.updateParticipantName(event.getOldAvailableDateTimes(),
                event.getNewAvailableDateTimes(),
                event.getParticipantName());
        timeTableRepository.save(timeTable);
```
이 부분이 시간교체시 TimeTable의 교체 로직에 해당합니다.
쿼리를 확인한 결과 delete쿼리가 제대로 나가지 않았습니다
즉 counting이 제대로 되지 않았던 이유는, 삭제되어야하는 엔티티가 제대로 삭제 되지 않았기 때문입니다
자세히 보니,
JPA에서 삭제를 먼저 수행하고, 그 다음에 도메인에서 삭제와 저장을 수행하고 다시 JPA에서 저장을 수행합니다. 찾아보니 이럴 경우 복수개의 엔티티를 삭제 시 문제가 발생할 수 있다고 합니다.
실제로도 복수 개의 데이터가 삭제되어야하는데, 전부 삭제가 되지 않는 경우도 있었습니다.
데이터 무결성에 문제가 생겼던 것으로 생각됩니다.

이렇게 삭제와 저장이 동시에 수행되어야하는 경우
작업 순서는 다음과 같이 처리되어야합니다

```
- 삭제할 엔티티와 관련된 엔티티들의 관계를 먼저 제거
- 해당 엔티티를 JPA를 통해 삭제
- 추가할 엔티티를 생성하고, 관련된 엔티티들의 관계를 설정
- 해당 엔티티를 JPA를 통해 저장
```

구글링을 통해 얻은 추가적인 내용입니다. 참고하면 좋을 것 같습니다.

```
삭제와 저장이 동시에 수행되는 경우
먼저 삭제 작업을 처리한 후에 추가 작업을 처리하는 것이 좋습니다. 그리고 삭제와 추가 작업은 서로 다른 트랜잭션으로 처리하는 것이 안전합니다. 특히, 삭제 작업을 먼저 처리하면서 엔티티의 관계를 제거하는 것이 중요합니다. 이것이 제대로 처리되지 않으면 데이터베이스 무결성에 문제가 발생할 수 있습니다.
```

다음은 변경된 부분입니다

```java
        timeTable.removeParticipantName(event.getOldAvailableDateTimes(), event.getParticipantName());
        for (Long timeInfoId : timeInfoIds) {
            timeInfoParticipantNameRepository.deleteByTimeInfoIdAndName(timeInfoId, event.getParticipantName());
        }

        timeTable.addParticipantName(event.getNewAvailableDateTimes(), event.getParticipantName());
        timeTableRepository.save(timeTable);
```

또한, availableTimes를 가져오는 부분에도 문제가 있었습니다.
삭제할 때 즉, 기존에 존재하는 availableTimes를 가져오는 경우에는 isEmpty() 로 값의 유무를 확인해야하고,
저장할 때 즉, 새로운 availableTimes를 가져오는 경우에는 is null 로 값의 유무를 확인해야 했습니다.
왜냐하면 이미 값이 존재하는 경우는 인스턴스가 생성되어 있기 때문입니다
해당 고친 부분은 해당 부분의 테스트도 수정해 놓았습니다

## 어떤 부분에 집중하여 리뷰해야 할까요?

위 설명을 참고하면 될 것 같습니다!

## (option) 이 부분은 주의해 주세요.

# 중요 !!
- 운영 배포될 때 joinColumn 바뀐 것 때문에 동작을 안할 수 있습니다 !
- 어차피 테스트용으로 사용하고 있었어서, 운영디비를 한번 날렸다가 다시 했으면 좋겠는데 가능할까요?

## (option) 참고자료

## (option) 결과

---

## RCA rule
- r: 꼭 반영해 주세요. 적극적으로 고려해 주세요.
- c: 웬만하면 반영해 주세요.
- a: 반영해도 좋고 안 해도 좋습니다. 사소한 의견입니다.
- 규칙
    - submit 할 코멘트들 중에서 1개라도 r이 포함되어 있다면 request change를 날린다.
    - r 이 하나도 없다면 approve를 한다.

2023-05-14 19:27 UTC, ssssujini99 commented
근데 해당 부분 수정하면서 교체 시 TimeTable 뿐만 아니라 AdjustmentResult 도 이벤트가 발생되면서 변경되는데, 해당 부분이 수정되면서 발생해야 하는 AdjustmentResult 도메인 이벤트를 호출하는 시점도 재고려해야할 것 같습니다
// todo 로 남겨놓았습니다
회의때 같이 얘기해봐용!

2023-05-21 23:54 UTC, dongho108 requested changes
count 문제를 로컬서버 상에서 테스트해봤는데 아직 문제가 좀 많은거같아요.

(24, 26일 9~12까지 모두 선택)
![스크린샷 2023-05-22 오전 8 47 50](https://github.com/dnd-side-project/dnd-8th-5-backend/assets/54317630/b9b4c180-d631-4cbd-9f26-1cd387a1055f)

(프론트도 요청은 제대로 보냈으나, 결과화면에서 듬성듬성 반영이 안되어있는 모습)
![스크린샷 2023-05-22 오전 8 52 01](https://github.com/dnd-side-project/dnd-8th-5-backend/assets/54317630/77d63c36-bb87-4d7c-bfed-eccb05582f3c)

여기 사진 보시면 프론트에서 요청은 잘 보냈는데 서버쪽에서 저장이 잘못되는지 문제가 아직 발생하네요..
이거 같이 찾아봐야할 것 같아요!

2023-05-31 14:23 UTC, dongho108 requested changes
궁금한 부분 리뷰 달아놨습니다.

테스트가 깨진 상태로 PR을 머지할 순 없어서 완성하고 머지해야될 것 같아요.!

2023-05-31 14:23 UTC, dongho108 commented on src/main/java/com/dnd/modutime/core/timetable/domain/DateInfo.java
> +        if (timesOrNull.isEmpty()) {
이거 왜 바껐나요?

2023-05-31 14:23 UTC, dongho108 commented on src/main/java/com/dnd/modutime/core/timetable/domain/DateInfo.java
> +        if (timesOrNull.isEmpty()) {
👀

2023-05-31 14:23 UTC, dongho108 commented on src/main/java/com/dnd/modutime/core/timetable/repository/TimeInfoParticipantNameRepository.java
> +    void deleteByTimeInfoIdAndName(Long timeInfoId, String name);
요기 변경 굿 👍

근데 변수명을 수정한 커밋 메세지는 fix나 에러 해결이 아니라 refactor 입니다 ~

2023-05-31 14:23 UTC, dongho108 commented on src/test/java/com/dnd/modutime/core/timetable/domain/DateInfoTest.java
> +                List.of()), "참여자1");
isEmpty가 추가되면서 변경되는 코드인 것 같아요

2023-05-31 15:13 UTC, dongho108 commented on src/main/java/com/dnd/modutime/core/timetable/domain/DateInfo.java
> +        if (timesOrNull.isEmpty()) {
```
삭제할 때 즉, 기존에 존재하는 availableTimes를 가져오는 경우에는 isEmpty() 로 값의 유무를 확인해야하고,
저장할 때 즉, 새로운 availableTimes를 가져오는 경우에는 is null 로 값의 유무를 확인해야 했습니다.
```
이 내용인 것 같은데 설명 한번 들어야되긋네요

2023-06-01 09:31 UTC, ssssujini99 commented on src/main/java/com/dnd/modutime/core/timetable/repository/TimeInfoParticipantNameRepository.java
> +    void deleteByTimeInfoIdAndName(Long timeInfoId, String name);
넵!!

2023-06-04 11:35 UTC, merged