fix: endTime으로 24시 선택 시 오류를 해결 및 교체 로직을 수정한다
dnd-side-project/dnd-8th-5-backend pull request #78
Opened 2023-07-01 19:26 UTC by ssssujini99

closed
- #77 

## 어떤 기능을 개발했나요?
Java의 LocalTime은 애초에 Time을 0 ~ 23까지밖에 받지 않는다.
지금까지의 로직은 startTime이 항상 endTime보다 작아야 방을 생성할 수 있게 했는데,
`23시 ~ 24시(=00시)`도 그리고 `23시 ~ 01시`도 허용이 가능하도록 변경해야한다.
이를 어떻게 해결해야할까?

## 어떻게 해결했나요?
- 로직 중 startTime < endTime 을 없애고, `startTime < endTime` 인 경우와 `startTime > endTime` 인 경우로 나눈다.

- `startTime < endTime` 인 경우, 참여자 시간 교체 시: 기존 로직 그대로 적용한다
- `startTime > endTime` 인 경우: 참여자가 교체하는 시간이 ![endTime, startTime) 면 된다
  - 두번째 설명을 덧붙이자면 23~01 인 경우, 참여자는 [01:00 - 23:00) 사이의 시간을 선택할 수 없다

그리고 추가된 두번째 로직에 대한 모든 테스트케이스를 작성하였습니다
각각 모든 시간에 대한 검증을 원했으며, 이를 위해 Parameterized Test를 적용하여 모든 시간에 대한 검증까지 마쳤습니다.

## 어떤 부분에 집중하여 리뷰해야 할까요?

## (option) 이 부분은 주의해 주세요.

## (option) 참고자료

## (option) 결과

---

## RCA rule
- r: 꼭 반영해 주세요. 적극적으로 고려해 주세요.
- c: 웬만하면 반영해 주세요.
- a: 반영해도 좋고 안 해도 좋습니다. 사소한 의견입니다.
- 규칙
    - submit 할 코멘트들 중에서 1개라도 r이 포함되어 있다면 request change를 날린다.
    - r 이 하나도 없다면 approve를 한다.

2023-07-03 07:30 UTC, dongho108 requested changes
고생하셨습니다 !!
몇가지 리뷰 남겼습니다.
그리고 프론트한테 24:00 코드 받아서 로컬에서 테스트 해보려고 합니다~!

2023-07-03 07:30 UTC, dongho108 commented on src/test/java/com/dnd/modutime/core/room/integration/RoomTimeValidatorTest.java
> +    void 시작시간이_끝시간보다_큰_경우_사이값의_시간이_포함되지_않으면_예외가_발생가_발생하지_않는다(LocalTime time) {
r: 오타발견 👀
```suggestion
    void 시작시간이_끝시간보다_큰_경우_사이값의_시간이_포함되지_않으면_예외가_발생하지_않는다(LocalTime time) {
```

2023-07-03 07:30 UTC, dongho108 commented on src/test/java/com/dnd/modutime/core/room/integration/RoomTimeValidatorTest.java
> +    void 끝시간이_00시이고_시작시간이_끝시간보다_큰_경우_사이값의_시간이_포함되지_않으면_예외가_발생하지_않는다(LocalTime time) {
c: 얘도 위의 테스트 있어서 굳이 필요 없을거같긴해요

2023-07-03 07:30 UTC, dongho108 commented on src/test/java/com/dnd/modutime/core/room/integration/RoomTimeValidatorTest.java
> +        Room room = getRoomByStartEndTime(LocalTime.of(23, 00), LocalTime.of(00, 00));
r: 픽스처 만들어서 사용하면 좋을 것 같아요
```suggestion
        Room room = getRoomByStartEndTime(_23_00, _00_00);
```

2023-07-03 07:30 UTC, dongho108 commented on src/test/java/com/dnd/modutime/core/room/integration/RoomTimeValidatorTest.java
> +    @ParameterizedTest
👍

2023-07-03 07:30 UTC, dongho108 commented on src/test/java/com/dnd/modutime/core/room/integration/RoomTimeValidatorTest.java
> +            Arguments.of(LocalTime.of(12, 30))
r: 얘도 픽스처로 바꿔서 사용하면 좋을 것 같아요
```suggestion
            Arguments.of(_11_00),
            Arguments.of(_11_30),
            Arguments.of(_12_00),
            Arguments.of(_12_30)
```

2023-07-03 10:31 UTC, ssssujini99 commented
- [ ] RoomTimeValidatorTest -> RoomTest 로 위치 변경
- [ ] parameter에서 time -> validTime, invalidTime 으로 가독성을 높였습니다

2023-07-03 11:01 UTC, ssssujini99 commented
- [ ] 모든 시간에 대해서 fixture를 이용하도록 변경했습니다

2023-07-03 11:03 UTC, dongho108 approved these changes
시간들 가독성 좋게 수정해주셔서 감사합니다 !
고생하셨습니다~

2023-07-03 11:03 UTC, dongho108 commented on src/test/java/com/dnd/modutime/core/room/integration/RoomTimeValidatorTest.java
> +    void 시작시간이_끝시간보다_큰_경우_사이값의_시간이_포함되면_예외가_발생한다(LocalTime time) {
r: MethodSource를 열어봐야 어떤 시간인지 아는게 불편한데, time 변수를 invalidTime 으로 바꾸면 어느정도 가독성도 챙길 수 있을 것 같습니다.

```suggestion
    void 시작시간이_끝시간보다_큰_경우_사이값의_시간이_포함되면_예외가_발생한다(LocalTime invalidTime) {
```

2023-07-17 03:48 UTC, dongho108 commented
`참여자가 교체하는 시간이 ![endTime, startTime) 면 된다` 가 무슨뜻일까요? 😅

2023-07-17 04:51 UTC, ssssujini99 commented
> 

== `endTime 보다 작고, startTime보다 같거나 크면 된다` 입니다

2023-07-17 05:26 UTC, dongho108 requested changes
작업하느라 고생 많으셨습니다!!
몇가지 가독성 부분 코멘트랑, 테스트 추가해야하는 부분 코멘트 남겼으니까 확인해주세요 ㅎㅎ

2023-07-17 05:26 UTC, dongho108 commented on src/main/java/com/dnd/modutime/core/room/application/RoomTimeTableInitializer.java
> +        }
r: 이 부분에 대한 `RoomTimeTableInitializer` 테스트가 있어야 할 것 같아요

2023-07-17 05:26 UTC, dongho108 commented on src/main/java/com/dnd/modutime/core/room/application/RoomTimeTableInitializer.java
> +            for (LocalTime time = LocalTime.of(0, 0); time.isBefore(endTime); time = time.plusMinutes(30)) {
r: 중복되는 시간은 변수로 빼도 되지 않을까요? 상수로 뺄 수 있을것 같아요.

```suggestion
            for (LocalTime time = startTime; !time.equals(ZERO_TIME); time = time.plusMinutes(30)) {
                timeInfos.add(new TimeInfo(time, new ArrayList<>()));
            }

            for (LocalTime time = ZERO_TIME; time.isBefore(endTime); time = time.plusMinutes(30)) {
```

2023-07-17 05:26 UTC, dongho108 commented on src/main/java/com/dnd/modutime/core/room/application/RoomTimeTableInitializer.java
> +            for (LocalTime time = startTime; !time.equals(LocalTime.of(0, 0)); time = time.plusMinutes(30)) {
c: 얘만 equals 비교인게 좀 어색하다고 느껴지기도하고, 혹시나(당장은 그럴일은 거의 없겠지만) time이 30분단위로 저장이 안되었을때 무한루프에 빠질 수 있을 것 같아요. 범위 조건으로 바꾸면 어떨까요?

2023-07-17 05:26 UTC, dongho108 commented on src/main/java/com/dnd/modutime/core/room/application/RoomTimeTableInitializer.java
> +        if (startTime.isAfter(endTime)) {
c: `if(isAfter) {~}` 쪽은 메서드로 따로 추출해도 될거같아요.
`addTimeInfosEndTimeToStartTime()` 이런 느낌으로요!

2023-07-17 05:26 UTC, dongho108 commented on src/main/java/com/dnd/modutime/core/room/domain/Room.java
> +            return (!startTime.isAfter(time)) && (time.isBefore(endTime));
c: 가독성을 위해 부정조건보단 긍정조건을 사용해보면 어떨까요?
```suggestion
            return startTime.isBefore(time) && endTime.isAfter(time) && startTime.isEqual(time);
```

2023-07-17 05:26 UTC, dongho108 commented on src/main/java/com/dnd/modutime/core/room/domain/Room.java
> +        return !(!endTime.isAfter(time) && time.isBefore(startTime));
c: 여기도 긍정조건을 사용해서 바꿀 수 있을 것 같아요!

2023-07-17 05:26 UTC, dongho108 commented on src/test/java/com/dnd/modutime/acceptance/AcceptanceSupporter.java
> +    }
👍👍👍👍

2023-07-21 18:36 UTC, ssssujini99 commented on src/main/java/com/dnd/modutime/core/room/application/RoomTimeTableInitializer.java
> +        if (startTime.isAfter(endTime)) {
해당 로직이 startTime 부터 - 24시까지 timeInfos를 더하는 내용이라
메서드 네이밍을 addTimeInfosStartToZeroTIme 으로 바꾸겠습니다!

2023-07-21 18:37 UTC, ssssujini99 commented on src/main/java/com/dnd/modutime/core/room/application/RoomTimeTableInitializer.java
> +        if (startTime.isAfter(endTime)) {
메서드로 빼니까 확실히 가독성이 너무좋아졌네요
좋은 피드백 넘 감사합니다 👍🏻👍🏻

2023-07-21 18:43 UTC, ssssujini99 commented on src/main/java/com/dnd/modutime/core/room/domain/Room.java
> +            return (!startTime.isAfter(time)) && (time.isBefore(endTime));
저부분이 일부로 가독성을 위해서 의미 자체로 표현해주기 위해서 저렇게 표현했습니다!
저거 다 긍정으로 바꾸면 오히려 이해하기가 어려워서요

(!startTime.isAfter(time)) && (time.isBefore(endTime));
이거로 보면, time이 startTime보다 크거나같고, endTime보다 작다
이렇게 직관적으로 바로 보이거든요!

2023-07-21 18:44 UTC, ssssujini99 commented on src/main/java/com/dnd/modutime/core/room/domain/Room.java
> +        return !(!endTime.isAfter(time) && time.isBefore(startTime));
이부분도 위 이유와 동일합니다!

2023-07-21 19:13 UTC, ssssujini99 commented on src/main/java/com/dnd/modutime/core/room/application/RoomTimeTableInitializer.java
> +            for (LocalTime time = startTime; !time.equals(LocalTime.of(0, 0)); time = time.plusMinutes(30)) {
이게 자정시간보다 작을때에 해당하는 조건인데,
00시보다 작다를 넣어야합니다
근데 이게 상대적인 시간이라 00시와 24시가 그래서 범위조건으로 비교가 안됩니다
그래서 자정과 동등비교조건을 써야만했습니다!

2023-07-21 19:14 UTC, ssssujini99 commented on src/main/java/com/dnd/modutime/core/room/application/RoomTimeTableInitializer.java
> +            for (LocalTime time = startTime; !time.equals(LocalTime.of(0, 0)); time = time.plusMinutes(30)) {
30분 단위 저장은 저희 도메인 로직이고, 이에대한 검증도 있으니
무한루프에 빠진다라는 가정은 이 부분이 아니라 처음 30분단위로 저장한다는 로직에 책임을 두어야하는게 맞는것같아요!

2023-07-21 19:24 UTC, ssssujini99 commented on src/main/java/com/dnd/modutime/core/room/application/RoomTimeTableInitializer.java
> +        if (startTime.isAfter(endTime)) {
해당 부분은 start > endTIme 일 때에 수행되어야하는 로직이므로
네이밍을 `addTimeInfosWhenStartTimeIsAfterEndTime` 로 했습니다!

2023-07-21 19:29 UTC, ssssujini99 commented on src/main/java/com/dnd/modutime/core/room/application/RoomTimeTableInitializer.java
> +        }
넵 해당 테스트 모두 TImeTableInitializerTest 에 추가했습니다

2023-07-23 07:16 UTC, dongho108 commented on src/main/java/com/dnd/modutime/core/room/domain/Room.java
> +            return (!startTime.isAfter(time)) && (time.isBefore(endTime));
`!startTime.isAfter(time)` 이 부분이 그대로 해석하면 startTime이 time의 이후가 아니다 라고 읽히는데,
time이 startTime보다 크거나 같다라는 말을 표현하려면 전부 time 기준으로 표현해도 괜찮을 것 같아요.
time이랑 startTime이랑 섞여서 더 헷갈리는 느낌이네요

그럼 이 방식은 어떤가요?
```suggestion
            return time.isEqual(StartTime) && time.isAfter(startTime)  && time.isBefore(endTime)
```

2023-07-23 07:31 UTC, dongho108 requested changes
리뷰 반영하느라 고생하셨어요!
1. 위에 시간비교 가독성이랑
2. 테스트코드가 아무 동작도 하지 않는 부분
리뷰 남겼습니다 확인해주세요 ㅎㅎ

2023-07-23 07:31 UTC, dongho108 commented on src/test/java/com/dnd/modutime/core/room/integration/RoomTimeTableInitializerTest.java
> +        );
r: 아무검증도 하지 않고있는데요 ?!

```suggestion
        assertAll(
            () -> assertThat(timeInfos.get(0).getTime().equals(_11_00)).isTrue()
            ...
        );
```

2023-07-23 07:31 UTC, dongho108 commented on src/test/java/com/dnd/modutime/core/room/integration/RoomTimeTableInitializerTest.java
> +            () -> assertThat(timeInfos.get(3).getTime().equals(_12_30))
r: 리스트의 요소를 하나씩 꺼내기보다는 containsExactly로 검증해야할 것 같습니다
만약 4개가 아니라 5개가 들어있어도 해당 테스트는 성공할 것 같습니다.

```suggestion
        List<TimeInfo> timeInfos = timeTable.getDateInfos().get(0).getTimeInfos();
        List<LocalTime> times = timeInfos.stream()
                .map(TimeInfo::getTime)
                .collect(Collectors.toList());

        // then
        assertThat(times).hasSize(4)
                .containsExactly(_11_00, _11_30, _12_00, _12_30);
```

2023-07-23 15:44 UTC, ssssujini99 commented on src/test/java/com/dnd/modutime/core/room/integration/RoomTimeTableInitializerTest.java
> +        );
isEqualTo 로 썻어야됐는데 그냥 equals로 해버렸네요 😅

2023-07-23 15:44 UTC, ssssujini99 commented on src/test/java/com/dnd/modutime/core/room/integration/RoomTimeTableInitializerTest.java
> +        );
isEqualTo로 수정해놓겠습니다!

2023-07-23 15:54 UTC, ssssujini99 commented on src/test/java/com/dnd/modutime/core/room/integration/RoomTimeTableInitializerTest.java
> +            () -> assertThat(timeInfos.get(3).getTime().equals(_12_30))
와 하나 더 배워갑니다 역시 최고입니다

2023-07-23 15:56 UTC, ssssujini99 commented
테스트부분 말씀해주신 containsExactly로 다 변경했습니다!! 훨씬 더 명확히 검증하는 방법인것같아요 👍🏻👍🏻

2023-07-25 02:25 UTC, dongho108 approved these changes
고생하셨습니다 !!
이거 개발서버 구축하고 프론트 코드랑 테스트 해본다음에 머지하죠 ㅎㅎ

2023-07-27 06:45 UTC, merged